### PR TITLE
Stylish a little bit

### PR DESCRIPTION
**Pull request by alexandresalome**
Add some colors

### CODE REVIEW

**Comment by alexandresalome** [comment]
what about using Twitter bootstrap?

please remember that later, twig extension may be moved out from this project to be reused on other applications. I don't want Twitter Bootstrap to be required for this.

**Comment by lyrixx** [comment]
Open 6 days ago ? How can I miss that.

of course +1 with bootstrap. But we have to remember that we build something very generic here.

I will have a look to the PR tomorow ;)

**Comment by lyrixx** [comment]
BTW, bootstrap are now on packagist ;)

**Comment by lyrixx** [comment]
I push on `css-rebased` the same branch but rebased again master.
Feel free to reset this branch to it

**Pull request merged**
