### PR TITLE
Implemented a tree browser

### PR DESCRIPTION
**Pull request by lyrixx**
Not finished yet

I decided to not use code mirror since the repository is
in a read only mode. I will add highligh.js in a second step.

Todo:

[]: Move some code to the theme

### CODE REVIEW

**Comment by lyrixx** [comment]
Need this PR to work fine: https://github.com/gitonomy/gitlib/pull/32

**Comment by lyrixx** [comment]
@alexandresalome can you do a code review ?

I does not like the code in the controller and in the template to render tree.
I have ported every thing from gitonomy.

Why I did not like:
- The controller is a bit fat
- The template need a lot of data (i think the commit is useless, see below)
- The code is very hard to read and totally no intuitive
- I Think there are design issues in gitlib:
  - Move (or duplicate) Commit::getLastModification to Tree::getLastModification (so is should be in the repository with proxy method)
  - :
    
    ```
    $tree = $repository->getRevision($revision)->getResolved()->getTree();
    $element = $tree->resolvePath($path);
    ```
    
    is very weird. I don't understand what happen here. Something like `$repository->getTree($rev, $path)` could be awesome.

What do you think ?

**Comment by alexandresalome** [comment]
I'll have a look at it by the end of the week

**Comment by alexandresalome** [comment]
Since I already implemented it for gitonomy, I understand the point of passing lot of information to the template, but every bit of it is required.

I consider it as good-enough to be merged, it's a good start point.

**Comment by lyrixx** [comment]
Ok.
But about 

```
$tree = $repository->getRevision($revision)->getResolved()->getTree();
$element = $tree->resolvePath($path); 
```

Can we do something ?

I did not try gitonomy, but we **should** move the git profiler to `Gitlib\Bridge\Symfony` to make it work with silex.

I think the tree browse use a lot of git call.

**Pull request merged**
